# Generated by Django 3.2.7 on 2021-09-20 08:25

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e7d5939b-ea8d-4366-b82d-7e075618bca5'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('preview', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('65df589b-8e24-48c6-92b8-404e08f3f100'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('aria', models.PositiveSmallIntegerField()),
                ('designer', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('preview', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='projects.style')),
            ],
        ),
    ]
