# Generated by Django 3.2.7 on 2021-09-15 12:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('aria', models.PositiveSmallIntegerField()),
                ('designer', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('preview', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
    ]
